language: go
go:
  - "1.13.x"

cache:
  directories:
    - $GOPATH/pkg/mod

go_import_path: github.com/ahirata/coredns-docker

before_install:
  - go get -t -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
